---
jobs:
- name: run-integration-tests
  public: true
  serial: true
  plan:
  - get: flask-test-source
    trigger: true
  - task: run-tests
    privileged: true
    config:
        platform: linux
        inputs:
        - name: flask-test-source
        image_resource:
            type: docker-image
            source:
              repository: saivarunk/postgres-python
              tag: latest
        run:
            path: flask-test-source/integration_tests.sh

- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: flask-test-source
    trigger: true
    passed: [run-integration-tests]
  - put: docker-image
    params:
      build: flask-test-source

resources:
- name: flask-test-source
  type: git
  source:
    uri: https://github.com/saivarunk/flask-test.git
    branch: master

- name: docker-image
  type: docker-image
  source:
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-create-flask-test-image}}