---
jobs:
- name: run-integration-tests
  public: true
  serial: true
  plan:
  - get: flask-test-source
    trigger: true
  - task: run-tests
    privileged: true
    config:
        platform: linux
        inputs:
        - name: flask-test-source
        image_resource:
            type: docker-image
            source:
              repository: python:3.6.4-alpine3.7
        run:
            path: sh
            args:
            - -exc
                - |
                    cd ./flask-test-source
                    pip install -r requirements.txt
                    python -m unittest integration_tests

- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: flask-test-source
    trigger: true
  - put: docker-image
    params:
      build: flask-test-source

resources:
- name: flask-test-source
  type: git
  source:
    uri: https://github.com/saivarunk/flask-test.git
    branch: master

- name: docker-image
  type: docker-image
  source:
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-create-flask-test-image}}